# Generated by Django 3.1.2 on 2020-11-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemodel',
            name='name',
            field=models.ManyToManyField(to='HealthApp.DiseaseModel'),
        ),
    ]
